name: Deploy Apptainer

on:
  workflow_call:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: create apptainer recipe
        uses: m-jahn/snakemake-github-action@fix_apptainer
        with:
          directory: .
          snakefile: workflow/Snakefile
          install-apptainer: true
          args: "--cores 1"
          task: containerize
          containerize-args: apptainer

      - name: create apptainer image
        shell: bash
        run: |
          sudo apt-get install -y uidmap
          apptainer build --fakeroot apptainer.sif apptainer.def

      - name: authenticate to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | apptainer registry login -u ${{ github.actor }} --password-stdin oras://ghcr.io

      - name: push apptainer to GHCR
        run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "Pushing apptainer to: oras://ghcr.io/${REPO}:latest"
          apptainer push apptainer.sif "oras://ghcr.io/${REPO}:latest"
